In [1]:
import numpy as np

In [2]:
myPythonList = [1,2,3,4]
print(myPythonList)

[1, 2, 3, 4]


In [3]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([1, 2, 3, 4])

In [4]:
a  = np.array([2,0,0,3])
print(a)

[2 0 0 3]


In [5]:
x=numpy_array_from_list + 30
print(x)

[31 32 33 34]


In [6]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [7]:
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [8]:
c = np.array([(1,0,8),
              (1,4,3)])
print(c)

[[1 0 8]
 [1 4 3]]


In [10]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)

(2, 2, 3)


(2, 2, 3)

In [11]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [12]:
import numpy as np
np.ones((1,2,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [13]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [15]:
import numpy as np
f = np.array([1,2,7])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 7 4 5 6]


In [16]:
import numpy as np
f = np.array([1,2,7])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 7]
 [4 5 6]]


In [17]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.38920191 4.43822243 4.85512852 4.1093654  5.05782291 4.86231577
 5.32708942 4.64117533 4.67704407 4.79736234]


In [18]:
A = np.matrix(np.ones((4,4)))
np.array(A)[2]=2  
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [21]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [23]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [24]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [25]:
np.logspace(3.0, 4.0, num=3)

array([ 1000.        ,  3162.27766017, 10000.        ])

In [26]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [27]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [28]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [29]:
print('Second column:', e[:,1])

Second column: [2 5]


In [30]:
print(e[1, :2])

[4 5]


In [31]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[3.96905073 5.18575001 5.50286249 4.97088595 4.31083647 4.94843721
 5.88762178 5.53696372 5.53748066 4.98949937]


In [32]:
print(np.min(normal_array)) 
print(np.max(normal_array)) 
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

3.9690507260189642
5.887621779920833
5.08393883902544
5.087624691342031
0.5588759952123239


In [33]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([2,4])
### 1*2+2*4
np.dot(f, g)

10

In [34]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [35]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [36]:
n_array = np.array([[50, 29], [30, 44]])
print("Numpy Matrix is:")
print(n_array)
det = np.linalg.det(n_array)  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [37]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]]) 
np.linalg.matrix_rank(mx)

3

In [38]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -2.57831463e-15  5.57979826e-17] [[-0.15115432  0.72704996  0.51747505 -0.06588506]
 [-0.34923733  0.28320876 -0.82375673 -0.31743721]
 [-0.54732033 -0.16063243  0.09508831  0.83252961]
 [-0.74540333 -0.60447363  0.21119337 -0.44920733]]


In [39]:
gfg = np.matrix('[6, 2; 3, 4]')
diag = gfg.diagonal()
print(diag)

[[6 4]]


In [40]:
gfg = np.matrix('[4, 1; 12, 3]')
trans = gfg.transpose()   
print(trans)

[[ 4 12]
 [ 1  3]]


In [41]:
gfg = np.matrix('[4, 1; 12, 3]')
tracem = gfg.trace()
print(tracem)

[[7]]
